### PR TITLE
Rochelle edits

### PR DESCRIPTION
**Pull request by marcus-crane**
I've completed all of Rochelle's suggested edits and they're ready to merge

### CODE REVIEW

**Review by vaishnavi-iyer — COMMENTED** [review]
haven't been able to read through all of it, due to time constraint, trust that the changes are not affecting the tolkit in any negative way

**Comment by marcus-crane** [comment]
@vaishnavi-iyer Thanks. It's just spelling errors and rewords rather than rewrites

**Comment by vaishnavi-iyer** [comment]
if you have got rid of the whole charter, then you need to change the tile as it is no longer relevant

**Comment by vaishnavi-iyer** [comment]
please change the tile and create a new pull request

**Comment by marcus-crane** [comment]
Ah sorry, will do

**Pull request merged**
